<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Eng.EFsExtensions.Libs.AirportsLib</RootNamespace>
    <AssemblyVersion>1.7.1.0</AssemblyVersion>
    <FileVersion>1.7.1.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="ESystem">
      <HintPath>..\..\DLLs\ESystem.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>